global class SubDivisionFormWrapper 
{
    @AuraEnabled global String Subdivisionname;
    @AuraEnabled global String BuildingName;
    @AuraEnabled global String County;
    @AuraEnabled global String State;
    @AuraEnabled global String URL;
    @AuraEnabled global String builderURL;
    @AuraEnabled global String BuilderName;
    @AuraEnabled global String BuilderPhoneNumber;
    @AuraEnabled global String BuilderEmailAddress;
    @AuraEnabled global String otherInformation;

    global SubDivisionFormWrapper(){
        
    }
}