public class testAccountAfterInsert {

    public static testmethod void testTrigger(){
        /*Account acc = new Account();
        acc.Name = 'TEST321';
        acc.Account_Name__c = 'Testing Account';
        acc.type = 'Residential';
        acc.Company_Type__c = 'Branch Office';
        acc.Shareholder_Board__c = 'No';
        acc.Street_Number__c = '6824';
        acc.Street_Name__c = 'Dean';
        acc.Zip__c = '20171';
        acc.City__c = 'Herndon';
        acc.State__c = 'VA';
        acc.County__c = 'Fairfax';
        acc.Country__c = 'UNITED STATES';
        acc.Phone = '5559991234';
        insert(acc);
        System.debug('acc before active: ' + acc);
        acc.Status__c = 'Active';
        update(acc);
        System.debug('acc after active: ' + acc);  */     
    }

}